### PR TITLE
Updated Block 2 & 3 Mess Menu as of 2 Oct 2023

### PR DESCRIPTION
**Pull request by xkaper001**
Hey Ayan this side,
I updated the mess menu as per the new menu which was put on notice board as on 2 Oct 2023

IMG-20231005-WA0017

Ayan Gupta
23BCY10295

### CODE REVIEW

**Comment by shenmareparas** [comment]
Thank you for expressing your interest in contributing to the project. Regrettably, I must inform you that the project has been officially closed as of September 21, 2023. Consequently, the app has been removed from the Play Store and will no longer receive updates. Furthermore, the associated website has been permanently discontinued.

**Comment by xkaper001** [comment]
> Thank you for expressing your interest in contributing to the project. Regrettably, I must inform you that the project has been officially closed as of September 21, 2023. Consequently, the app has been removed from the Play Store and will no longer receive updates. Furthermore, the associated website has been permanently discontinued.

but why any particular reason? it's useful app for fresher

**Comment by shenmareparas** [comment]
Got into Trouble with college

**Comment by shenmareparas** [comment]
> > Thank you for expressing your interest in contributing to the project. Regrettably, I must inform you that the project has been officially closed as of September 21, 2023. Consequently, the app has been removed from the Play Store and will no longer receive updates. Furthermore, the associated website has been permanently discontinued.
> 
> but why any particular reason? it's useful app for fresher


Got into Trouble with college

**Comment by xkaper001** [comment]
> > > Thank you for expressing your interest in contributing to the project. Regrettably, I must inform you that the project has been officially closed as of September 21, 2023. Consequently, the app has been removed from the Play Store and will no longer receive updates. Furthermore, the associated website has been permanently discontinued.
> > 
> > 
> > but why any particular reason? it's useful app for fresher
> 
> Got into Trouble with college

Damnnn 💀 Okay

**Comment by shenmareparas** [comment]
> > > > Thank you for expressing your interest in contributing to the project. Regrettably, I must inform you that the project has been officially closed as of September 21, 2023. Consequently, the app has been removed from the Play Store and will no longer receive updates. Furthermore, the associated website has been permanently discontinued.
> > > 
> > > 
> > > but why any particular reason? it's useful app for fresher
> > 
> > 
> > Got into Trouble with college
> 
> Damnnn 💀 Okay

It is what it is

**Pull request closed without merging**
